repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/isort.git
  rev: 5.10.1
  hooks:
  - id: isort

- repo: https://github.com/pre-commit/mirrors-mypy.git
  rev: v0.961
  hooks:
  - id: mypy

- repo: https://github.com/Lucas-C/pre-commit-hooks.git
  rev: v1.3.0
  hooks:
  - id: remove-crlf
  - id: remove-tabs
