# Settings common for Python test code.

SERVER_HOST = "192.168.30.10"
SERVER_PORT = 502

# values from logging.h
LOG_BUFFER_SIZE = 128
LOG_BUFFER_CNT = 96

# values from modbus-thread.h
DISCRETE_INPUT_START = 100
DISCRETE_INPUT_NR = 128
COIL_START = 200
COIL_NR = 32
REG_INPUT_START = 1000
REG_INPUT_NREGS = 6144
REG_HOLDING_START = 8000
REG_HOLDING_NREGS = 128

# values from modbus_mappings.h
MODBUS_INPUT_LOGSTATUS_ADDR = DISCRETE_INPUT_START
MODBUS_INPUT_LOGSTATUS_LEN = LOG_BUFFER_CNT

MODBUS_INPUT_FWUPDATE_STATE_ADDR = MODBUS_INPUT_LOGSTATUS_ADDR + MODBUS_INPUT_LOGSTATUS_LEN
MODBUS_INPUT_FWUPDATE_STATE_LEN = 2

MODBUS_INPUT_LOGBUF_ADDR = REG_INPUT_START
MODBUS_INPUT_LOGBUF_LEN = (LOG_BUFFER_SIZE * LOG_BUFFER_CNT) / 2

MODBUS_HOLDING_CMD_ADDR = REG_HOLDING_START
MODBUS_HOLDING_CMD_LEN = 32

MODBUS_HOLDING_FWUPDATE_ADDR = MODBUS_HOLDING_CMD_ADDR + MODBUS_HOLDING_CMD_LEN
MODBUS_HOLDING_FWUPDATE_LEN = int(140 / 2)

MODBUS_TIMEOUT_COUNTER = 20
MODBUS_TIMEOUT_TIME = 2
